export const fallbackContent = {
  profile: {
    name: "Saumya Mirajkar",
    role: "Computer Engineering & IoT Student",
    tagline: "I build sensor-driven hardware and modern web applications.",
    location: "Pune, Maharashtra",
    email: "saumyamir25@gmail.com",
    phone: "+91 98928 14242",
    resume_url: "/resume/Saumya_Mirajkar_Resume.pdf",
    resume: {
      id: "active",
      fileName: "Saumya_Mirajkar_Resume.pdf",
      fileUrl: "/resume/Saumya_Mirajkar_Resume.pdf",
      storagePath: "canonical",
      uploadedAt: "2026-10-08T00:00:00.000Z",
      updatedAt: "2026-10-08T00:00:00.000Z",
      published: true,
      version: "1.0",
    },
    avatar: "/profile.jpg",
    portfolio_url: "https://saumya-mirajkar-portfolio.pages.dev",
    summary:
      "Computer Engineering and IoT diploma student with hands-on experience in web development, Python, C/C++, JavaScript, React, and embedded systems. Completed a web development internship at Big Bang Tech Solutions involving web/mobile application development, project planning and testing, and cross-functional team collaboration.",
    bio: "I'm Saumya Mirajkar, a Computer Engineering & IoT student who enjoys turning ideas into practical digital products. I work across web development, software, automation, and IoT, with a focus on building clean, useful, and real-world solutions.",
    interests: [
      "Web Development",
      "React & Frontend Engineering",
      "Embedded Systems & IoT",
      "Python Programming",
      "Sensor Integration",
      "Cloud & AI Technologies",
    ],
    career_goals: [
      "Grow into a software engineer shipping robust, user-centric web applications.",
      "Expand expertise in full-stack architecture, cloud services, and IoT systems.",
      "Collaborate with engineering teams to solve complex real-world challenges.",
    ],
    highlights: [
      { value: "4", label: "Semesters Completed" },
      { value: "4", label: "Programming Languages" },
      { value: "4", label: "Certifications Earned" },
      { value: "3", label: "Featured Projects" },
    ],
    socials: {
      github: "https://github.com/saumyamirajkar",
      email: "mailto:saumyamir25@gmail.com",
      phone: "tel:+919892814242",
    },
  },
  skills: [
    { id: 1, name: "C", category: "Languages", keywords: ["systems", "embedded"], icon: "c", visible: true, featured: true, sortOrder: 1, order: 1 },
    { id: 2, name: "C++", category: "Languages", keywords: ["OOP", "embedded"], icon: "cpp", visible: true, featured: true, sortOrder: 2, order: 2 },
    { id: 3, name: "Python", category: "Languages", keywords: ["automation", "backend", "scripts"], icon: "python", visible: true, featured: true, sortOrder: 3, order: 3 },
    { id: 4, name: "JavaScript", category: "Languages", keywords: ["web", "frontend", "ES6+"], icon: "javascript", visible: true, featured: true, sortOrder: 4, order: 4 },
    { id: 5, name: "HTML", category: "Web Development", keywords: ["semantic markup", "HTML5"], icon: "html", visible: true, featured: true, sortOrder: 5, order: 5 },
    { id: 6, name: "CSS", category: "Web Development", keywords: ["responsive", "styling", "CSS3"], icon: "css", visible: true, featured: true, sortOrder: 6, order: 6 },
    { id: 7, name: "React", category: "Web Development", keywords: ["components", "hooks", "frontend"], icon: "react", visible: true, featured: true, sortOrder: 7, order: 7 },
    { id: 8, name: "Firebase", category: "Backend / Database", keywords: ["auth", "firestore", "cloud"], icon: "firebase", visible: true, featured: true, sortOrder: 8, order: 8 },
    { id: 9, name: "Arduino", category: "IoT / Hardware", keywords: ["microcontrollers", "circuits"], icon: "arduino", visible: true, featured: true, sortOrder: 9, order: 9 },
    { id: 10, name: "Sensors", category: "IoT / Hardware", keywords: ["moisture", "rain", "automation"], icon: "sensor", visible: true, featured: true, sortOrder: 10, order: 10 },
    { id: 11, name: "Git", category: "Tools & Platforms", keywords: ["version control"], icon: "git", visible: true, featured: false, sortOrder: 11, order: 11 },
    { id: 12, name: "GitHub", category: "Tools & Platforms", keywords: ["collaboration", "open source"], icon: "github", visible: true, featured: false, sortOrder: 12, order: 12 },
    { id: 13, name: "Vite", category: "Tools & Platforms", keywords: ["bundling", "build tool"], icon: "vite", visible: true, featured: false, sortOrder: 13, order: 13 },
    { id: 14, name: "Microsoft Excel", category: "Tools & Platforms", keywords: ["data", "sheets"], icon: "excel", visible: true, featured: false, sortOrder: 14, order: 14 },
    { id: 15, name: "Microsoft PowerPoint", category: "Tools & Platforms", keywords: ["presentations"], icon: "powerpoint", visible: true, featured: false, sortOrder: 15, order: 15 },
  ],
  projects: [
    {
      id: 1,
      title: "AutoInvoice — Invoice & Client Management Web App",
      category: "React Web App",
      short_description:
        "Web app for managing clients, invoices, and payments with PDF generation, email workflow, and UPI payments.",
      description:
        "Built a comprehensive web application for managing clients, invoices, and payment information. Added client-side invoice PDF generation, automated email invoice workflows, and UPI payment functionality.",
      problem:
        "Small businesses and freelancers lack simple, lightweight tools to manage client records, generate invoices on the fly, and collect direct UPI payments.",
      approach:
        "Engineered a responsive React and Vite web app utilizing jsPDF for high-fidelity client invoice generation and streamlined email and UPI payment workflows.",
      result:
        "Simplified the end-to-end invoicing lifecycle from client entry to instant PDF export and direct UPI payment receipt.",
      summary:
        "React and Vite web app for managing clients, generating invoice PDFs with jsPDF, and handling email and UPI payments.",
      features: [
        "Client and customer management directory",
        "Dynamic invoice calculation with customizable rates",
        "Instant invoice PDF generation powered by jsPDF",
        "Email invoice delivery workflow",
        "UPI payment integration and QR generation",
      ],
      learned:
        "Client-side document rendering with jsPDF, component state architecture in React, Vite build optimization, and UPI payment deep-linking.",
      contribution:
        "Designed and implemented the complete frontend architecture, invoice calculation algorithms, and PDF generation pipeline.",
      technologies: ["React", "Vite", "JavaScript", "jsPDF"],
      github_url: "https://github.com/saumyamirajkar",
      live_url: "",
      image: "/projects/autoinvoice.svg",
      featured: true,
      order: 0,
    },
    {
      id: 2,
      title: "LifeTrackr — Personal Productivity Web App",
      category: "Full-Stack Web App",
      short_description:
        "Personal dashboard for tracking tasks, habits, finance, journal entries, and productivity with Firebase cloud storage.",
      description:
        "Developed a personal dashboard for tracking tasks, habits, finance, journal entries, and productivity. Implemented authentication, cloud data storage, and a responsive interface.",
      problem:
        "Personal productivity tools are often fragmented across multiple disconnected apps, making it hard to maintain consistent habits, track finances, and analyze progress.",
      approach:
        "Unified tasks, habit streaks, expense/income tracking, daily journaling, and performance tracking into a responsive web interface powered by Firebase.",
      result:
        "A unified personal productivity dashboard delivering real-time progress tracking, habit streaks, financial clarity, and daily logging.",
      summary:
        "Personal productivity web app built with HTML, CSS, JavaScript, and Firebase for tracking tasks, habits, finance, and journals.",
      features: [
        "Task Management with priority lists and status workflows",
        "Habit Tracker with streak calculations and daily completion logs",
        "Personal Finance Tracker for income, expenses, and savings goals",
        "Daily Journaling and reflection log",
        "Productivity Analytics with visual progress trends",
        "Firebase Authentication and Cloud Firestore data persistence",
      ],
      learned:
        "Firebase authentication and cloud database security rules, asynchronous JavaScript state management, and responsive CSS UI engineering.",
      contribution:
        "Designed the UI/UX, implemented Firebase authentication and real-time database syncing, and engineered productivity widgets.",
      technologies: ["HTML", "CSS", "JavaScript", "Firebase"],
      github_url: "https://github.com/saumyamirajkar",
      live_url: "",
      image: "/projects/lifetrackr.svg",
      featured: true,
      order: 1,
    },
    {
      id: 3,
      title: "Automatic Car Wiper System",
      category: "Hardware & IoT",
      short_description:
        "Automatic wiper system using moisture and rain sensors with Arduino to control wipers according to detected rain.",
      description:
        "Built an automatic wiper system using moisture and rain sensors. Used Arduino microcontroller logic to control the wiper mechanism according to detected rain.",
      problem:
        "Manual wipers demand constant driver attention the moment rain starts, causing distraction in adverse weather conditions.",
      approach:
        "Integrated moisture and rain sensors with an Arduino microcontroller, writing embedded control firmware in C/C++ to drive the wiper motor based on rainfall intensity.",
      result:
        "The wiper engages automatically the instant rain is detected, removing manual driver distraction and improving safety.",
      summary:
        "Arduino-based wiper system using moisture and rain sensors to detect rainfall and activate wipers automatically.",
      features: [
        "Automatic wiper activation on rainfall detection",
        "Moisture and rain sensor signal processing",
        "Real-time weather condition sensing",
        "Removes manual wiper stalk operation",
      ],
      learned:
        "Embedded C/C++ programming, analog-to-digital sensor signal interpretation, relay motor driving, and circuit prototyping.",
      contribution:
        "Assembled sensor circuits, programmed the Arduino firmware, and calibrated rain sensitivity thresholds.",
      technologies: ["Arduino", "C/C++", "Sensors"],
      github_url: "https://github.com/saumyamirajkar",
      live_url: "",
      image: "/projects/car-wiper.svg",
      featured: true,
      order: 2,
    },
  ],
  experience: [
    {
      id: 1,
      company: "Big Bang Tech Solutions Pvt. Ltd.",
      position: "Web Development Intern",
      location: "Pune, Maharashtra",
      start_date: "May 2026",
      end_date: "Sep 2026",
      current: false,
      responsibilities: [
        "Assisted with web and mobile application development.",
        "Supported project planning, implementation and testing.",
        "Conducted technical research and helped with technical solutions.",
        "Worked with development and design teams on project tasks.",
      ],
      technologies: ["Web Development", "JavaScript", "Python", "Git"],
      order: 0,
    },
  ],
  education: [
    {
      id: 1,
      institution: "Cusrow Wadia Institute of Technology",
      degree: "Diploma in Computer Engineering & IoT",
      location: "Pune, Maharashtra",
      start_date: "2023",
      end_date: "Present",
      current: true,
      details: [
        "Computer Engineering & IoT diploma track with coursework spanning programming, web development, embedded systems and networking.",
      ],
      grades: { "Sem 1": "70.82%", "Sem 2": "71.65%", "Sem 3": "65.89%", "Sem 4": "64.98%" },
      order: 0,
    },
    {
      id: 2,
      institution: "S S Ajmera High School",
      degree: "SSC",
      location: "Pune, Maharashtra",
      start_date: "2023",
      end_date: "2023",
      current: false,
      details: [],
      grades: { SSC: "79.80%" },
      order: 1,
    },
  ],
  certifications: [
    {
      id: 1,
      name: "IBM AI Developer Professional Certificate",
      organization: "IBM / Coursera",
      issuer: "Coursera",
      provider: "Coursera",
      category: "AI",
      date: "OCT 2026",
      issueDate: "OCT 2026",
      credential_url: "",
      verificationUrl: "",
      featured: true,
      visible: true,
      verified: true,
      order: 0,
      sortOrder: 0,
    },
    {
      id: 2,
      name: "Google AI Professional Certificate",
      organization: "Google",
      issuer: "Google",
      provider: "Google",
      category: "AI",
      date: "JUL 2026",
      issueDate: "JUL 2026",
      credential_url: "",
      verificationUrl: "",
      featured: true,
      visible: true,
      verified: true,
      order: 1,
      sortOrder: 1,
    },
    {
      id: 3,
      name: "Introduction to Cloud Computing",
      organization: "IBM",
      issuer: "IBM",
      provider: "IBM",
      category: "Cloud",
      date: "AUG 2026",
      issueDate: "AUG 2026",
      credential_url: "",
      verificationUrl: "",
      featured: true,
      visible: true,
      verified: true,
      order: 2,
      sortOrder: 2,
    },
    {
      id: 4,
      name: "Python Essentials 1",
      organization: "Cisco Networking Academy",
      issuer: "Cisco",
      provider: "Cisco",
      category: "Programming",
      date: "JUL 2026",
      issueDate: "JUL 2026",
      credential_url: "",
      verificationUrl: "",
      featured: true,
      visible: true,
      verified: true,
      order: 3,
      sortOrder: 3,
    },
  ],
};